/////////////////////////////////////////////////////////////////////////////
// Copyright © 2026 by W. T. Block, all rights reserved
/////////////////////////////////////////////////////////////////////////////
#include "pch.h"
#include "ColorPlus.h"

CColorPlus::CColorPlus()
{
	// initialize GDI dash lookup table
	vector<pair<CString, Gdiplus::ARGB> > arrColors =
	{
		{ L"AliceBlue", AliceBlue },
		{ L"AntiqueWhite", AntiqueWhite },
		{ L"Aqua", Aqua },
		{ L"Aquamarine", Aquamarine },
		{ L"Azure", Azure },
		{ L"Beige", Beige },
		{ L"Bisque", Bisque },
		{ L"Black", Black },
		{ L"BlanchedAlmond", BlanchedAlmond },
		{ L"Blue", Blue },
		{ L"BlueViolet", BlueViolet },
		{ L"Brown", Brown },
		{ L"BurlyWood", BurlyWood },
		{ L"CadetBlue", CadetBlue },
		{ L"Chartreuse", Chartreuse },
		{ L"Chocolate", Chocolate },
		{ L"Coral", Coral },
		{ L"CornflowerBlue", CornflowerBlue },
		{ L"Cornsilk", Cornsilk },
		{ L"Crimson", Crimson },
		{ L"Cyan", Cyan },
		{ L"DarkBlue", DarkBlue },
		{ L"DarkCyan", DarkCyan },
		{ L"DarkGoldenrod", DarkGoldenrod },
		{ L"DarkGray", DarkGray },
		{ L"DarkGreen", DarkGreen },
		{ L"DarkKhaki", DarkKhaki },
		{ L"DarkMagenta", DarkMagenta },
		{ L"DarkOliveGreen", DarkOliveGreen },
		{ L"DarkOrange", DarkOrange },
		{ L"DarkOrchid", DarkOrchid },
		{ L"DarkRed", DarkRed },
		{ L"DarkSalmon", DarkSalmon },
		{ L"DarkSeaGreen", DarkSeaGreen },
		{ L"DarkSlateBlue", DarkSlateBlue },
		{ L"DarkSlateGray", DarkSlateGray },
		{ L"DarkTurquoise", DarkTurquoise },
		{ L"DarkViolet", DarkViolet },
		{ L"DeepPink", DeepPink },
		{ L"DeepSkyBlue", DeepSkyBlue },
		{ L"DimGray", DimGray },
		{ L"DodgerBlue", DodgerBlue },
		{ L"Firebrick", Firebrick },
		{ L"FloralWhite", FloralWhite },
		{ L"ForestGreen", ForestGreen },
		{ L"Fuchsia", Fuchsia },
		{ L"Gainsboro", Gainsboro },
		{ L"GhostWhite", GhostWhite },
		{ L"Gold", Gold },
		{ L"Goldenrod", Goldenrod },
		{ L"Gray", Gray },
		{ L"Green", Green },
		{ L"GreenYellow", GreenYellow },
		{ L"Honeydew", Honeydew },
		{ L"HotPink", HotPink },
		{ L"IndianRed", IndianRed },
		{ L"Indigo", Indigo },
		{ L"Ivory", Ivory },
		{ L"Khaki", Khaki },
		{ L"Lavender", Lavender },
		{ L"LavenderBlush", LavenderBlush },
		{ L"LawnGreen", LawnGreen },
		{ L"LemonChiffon", LemonChiffon },
		{ L"LightBlue", LightBlue },
		{ L"LightCoral", LightCoral },
		{ L"LightCyan", LightCyan },
		{ L"LightGoldenrodYellow", LightGoldenrodYellow },
		{ L"LightGray", LightGray },
		{ L"LightGreen", LightGreen },
		{ L"LightPink", LightPink },
		{ L"LightSalmon", LightSalmon },
		{ L"LightSeaGreen", LightSeaGreen },
		{ L"LightSkyBlue", LightSkyBlue },
		{ L"LightSlateGray", LightSlateGray },
		{ L"LightSteelBlue", LightSteelBlue },
		{ L"LightYellow", LightYellow },
		{ L"Lime", Lime },
		{ L"LimeGreen", LimeGreen },
		{ L"Linen", Linen },
		{ L"Magenta", Magenta },
		{ L"Maroon", Maroon },
		{ L"MediumAquamarine", MediumAquamarine },
		{ L"MediumBlue", MediumBlue },
		{ L"MediumOrchid", MediumOrchid },
		{ L"MediumPurple", MediumPurple },
		{ L"MediumSeaGreen", MediumSeaGreen },
		{ L"MediumSlateBlue", MediumSlateBlue },
		{ L"MediumSpringGreen", MediumSpringGreen },
		{ L"MediumTurquoise", MediumTurquoise },
		{ L"MediumVioletRed", MediumVioletRed },
		{ L"MidnightBlue", MidnightBlue },
		{ L"MintCream", MintCream },
		{ L"MistyRose", MistyRose },
		{ L"Moccasin", Moccasin },
		{ L"NavajoWhite", NavajoWhite },
		{ L"Navy", Navy },
		{ L"OldLace", OldLace },
		{ L"Olive", Olive },
		{ L"OliveDrab", OliveDrab },
		{ L"Orange", Orange },
		{ L"OrangeRed", OrangeRed },
		{ L"Orchid", Orchid },
		{ L"PaleGoldenrod", PaleGoldenrod },
		{ L"PaleGreen", PaleGreen },
		{ L"PaleTurquoise", PaleTurquoise },
		{ L"PaleVioletRed", PaleVioletRed },
		{ L"PapayaWhip", PapayaWhip },
		{ L"PeachPuff", PeachPuff },
		{ L"Peru", Peru },
		{ L"Pink", Pink },
		{ L"Plum", Plum },
		{ L"PowderBlue", PowderBlue },
		{ L"Purple", Purple },
		{ L"Red", Red },
		{ L"RosyBrown", RosyBrown },
		{ L"RoyalBlue", RoyalBlue },
		{ L"SaddleBrown", SaddleBrown },
		{ L"Salmon", Salmon },
		{ L"SandyBrown", SandyBrown },
		{ L"SeaGreen", SeaGreen },
		{ L"SeaShell", SeaShell },
		{ L"Sienna", Sienna },
		{ L"Silver", Silver },
		{ L"SkyBlue", SkyBlue },
		{ L"SlateBlue", SlateBlue },
		{ L"SlateGray", SlateGray },
		{ L"Snow", Snow },
		{ L"SpringGreen", SpringGreen },
		{ L"SteelBlue", SteelBlue },
		{ L"Tan", Tan },
		{ L"Teal", Teal },
		{ L"Thistle", Thistle },
		{ L"Tomato", Tomato },
		{ L"Transparent", Transparent },
		{ L"Turquoise", Turquoise },
		{ L"Violet", Violet },
		{ L"Wheat", Wheat },
		{ L"White", White },
		{ L"WhiteSmoke", WhiteSmoke },
		{ L"Yellow", Yellow },
		{ L"YellowGreen", YellowGreen },
	};

	// cross reference the color names with their corresponding enumeration
	for (auto& node : arrColors)
	{
		{
			CString csKey = node.first;
			shared_ptr<Gdiplus::ARGB> pColor = make_shared<Gdiplus::ARGB>(node.second);
			m_mapColors.add(csKey, pColor);
		}

		{
			Gdiplus::ARGB key = node.second;
			shared_ptr<CString> pARGB = make_shared<CString>(node.first);
			m_mapARGB.add(key, pARGB);
		}
	}
}
